export const countries = [
	{
		applicants: 393,
		forgery: 3,
		percentageForgery: 0.007633587786259542,
		id: 'AW',
		name: 'Aruba',
		conversion: 85.02,
		measure: '%',
		doctype: 'Passport\nID card\nDriving license',
		doctypeCount: 3,
	},
	{
		applicants: 8474,
		forgery: 144,
		percentageForgery: 0.01699315553457635,
		id: 'AF',
		name: 'Afghanistan',
		conversion: 83.16,
		measure: '%',
		doctype: 'Passport\n• Diplomatic Passport\nID card\nDriving license',
		doctypeCount: 4,
	},
	{
		applicants: 5918,
		forgery: 61,
		percentageForgery: 0.010307536329841162,
		id: 'AO',
		name: 'Angola',
		conversion: 92.55,
		measure: '%',
		doctype: 'Passport\n• Diplomatic Passport\nID card\n• Consul ID\nDriving license\nResidence permit',
		doctypeCount: 6,
	},
	{
		applicants: 144,
		forgery: 1,
		percentageForgery: 0.006944444444444444,
		id: 'AI',
		name: 'Anguilla',
		conversion: 84.62,
		measure: '%',
		doctype: 'Driving license',
		doctypeCount: 1,
	},
	{
		applicants: 2688,
		forgery: 74,
		percentageForgery: 0.027529761904761904,
		id: 'AX',
		name: 'Aland Islands',
		conversion: 81.39,
		measure: '%',
		doctype: 'Passport\nID card\nDriving license\nResidence permit',
		doctypeCount: 4,
	},
	{
		applicants: 15077,
		forgery: 69,
		percentageForgery: 0.0045765072627180475,
		id: 'AL',
		name: 'Albania',
		conversion: 97.75,
		measure: '%',
		doctype: 'Passport\nID card\nDriving license',
		doctypeCount: 3,
	},
	{
		applicants: 1931,
		forgery: 10,
		percentageForgery: 0.005178663904712584,
		id: 'AD',
		name: 'Andorra',
		conversion: 91.53,
		measure: '%',
		doctype: 'Passport\nDriving license\nResidence permit',
		doctypeCount: 3,
	},
	// {
	// 	applicants: 68,
	// 	forgery: 1,
	// 	percentageForgery: 0.014705882352941176,
	// 	id: 'AN',
	// 	name: 'Netherlands Antilles',
	// 	conversion: 0,
	// 	measure: '%',
	// 	doctype: 'Passport\nID card',
	// 	doctypeCount: 2,
	// },
	{
		applicants: 297191,
		forgery: 695,
		percentageForgery: 0.002338563415446632,
		id: 'AE',
		name: 'United Arab Emirates',
		conversion: 90.09,
		measure: '%',
		doctype:
			'Passport\nID card\nDriving license\n• Pilot license\n• Ajman Police\nResidence permit\n• Golden Card\n• Residence sticker - should be accompanied by main page of the document',
		doctypeCount: 8,
	},
	{
		applicants: 297384,
		forgery: 145,
		percentageForgery: 0.00048758507518898125,
		id: 'AR',
		name: 'Argentina',
		conversion: 96.37,
		measure: '%',
		doctype:
			'Passport\n• Diplomatic Passport\n• Provisional Passport (Pasaporte de Emergencia)\nID card\n• Booklet ID\n• Diplomatic ID\nDriving license\n• Provincia de Entre Rios\n• Ciudad Autonoma de Buenos Aires\n• Santa Fe\n• Provincia de Buenos Aires\n• Santiago del Estero\n• Cordoba\n• Provincia de Mendoza\nResidence permit',
		doctypeCount: 16,
	},
	{
		applicants: 36699,
		forgery: 77,
		percentageForgery: 0.002098149813346413,
		id: 'AM',
		name: 'Armenia',
		conversion: 96.44,
		measure: '%',
		doctype: 'Passport\nID card\n• Refugee ID, needs notarized translation\nDriving license\nResidence permit',
		doctypeCount: 5,
	},
	{
		applicants: 512,
		forgery: 10,
		percentageForgery: 0.01953125,
		id: 'AS',
		name: 'American Samoa',
		conversion: 85.47,
		measure: '%',
		doctype: 'Passport\nImmigration identification card\nDriving license',
		doctypeCount: 3,
	},
	{
		applicants: 2494492,
		forgery: 376,
		percentageForgery: 0.00015073209294718122,
		id: 'AQ',
		name: 'Antarctica',
		conversion: 0,
		measure: '%',
		doctype: '',
		doctypeCount: 0,
	},
	{
		applicants: 29,
		forgery: 0,
		percentageForgery: 0,
		id: 'TF',
		name: 'French Southern Territories',
		conversion: 84.37,
		measure: '%',
		doctype: '',
		doctypeCount: 0,
	},
	{
		applicants: 674,
		forgery: 2,
		percentageForgery: 0.002967359050445104,
		id: 'AG',
		name: 'Antigua and Barbuda',
		conversion: 84.82,
		measure: '%',
		doctype: 'Passport\nVoter card\nDriving license',
		doctypeCount: 3,
	},
	{
		applicants: 178270,
		forgery: 452,
		percentageForgery: 0.002535479890054412,
		id: 'AU',
		name: 'Australia',
		conversion: 92.81,
		measure: '%',
		doctype:
			'Passport\nID card\n• Firearms license\n• Photo Card\n• Proof of Age card\n• Keypass ID\n• High risk work license\n• Diplomatic ID\nDriving license\n• New South Wales\n• Queensland\n• South Australia\n• Tasmania\n• Victoria\n• Western Australia\n• Northern Territory\n• Australian Capital Territory\n\nResidence permit',
		doctypeCount: 19,
	},
	{
		applicants: 49457,
		forgery: 190,
		percentageForgery: 0.00384172109104879,
		id: 'AT',
		name: 'Austria',
		conversion: 95.34,
		measure: '%',
		doctype:
			'Passport\n• Emergency Passport\nID card\n• Refugee ID (grey)\n• Diplomatic ID\n• Disabled Person Card\nDriving license\nResidence permit',
		doctypeCount: 8,
	},
	{
		applicants: 64562,
		forgery: 113,
		percentageForgery: 0.0017502555682909452,
		id: 'AZ',
		name: 'Azerbaijan',
		conversion: 96.7,
		measure: '%',
		doctype: 'Passport\nID card\nDriving license\nResidence permit',
		doctypeCount: 4,
	},
	{
		applicants: 1437,
		forgery: 15,
		percentageForgery: 0.010438413361169102,
		id: 'BI',
		name: 'Burundi',
		conversion: 75.32,
		measure: '%',
		doctype: 'Passport\nEmergency Passport\nDriving license',
		doctypeCount: 3,
	},
	{
		applicants: 107321,
		forgery: 300,
		percentageForgery: 0.002795352260974087,
		id: 'BE',
		name: 'Belgium',
		conversion: 96.4,
		measure: '%',
		doctype:
			"Passport\nID card\n• Carte d'identité diplomatique (spéciale)\nDriving license\n• Provisional\nResidence permit\n• E Card (EU Citizen)\n• F Card (Member of EU Citizen Family)\n• E Plus Card (EU Citizen)",
		doctypeCount: 9,
	},
	{
		applicants: 28583,
		forgery: 84,
		percentageForgery: 0.0029388097820382745,
		id: 'BJ',
		name: 'Benin',
		conversion: 94.55,
		measure: '%',
		doctype:
			'Passport\nID card\n• Voter ID\n• ECOWAS ID\n• Certificate D’Identification Personnelle\n• Consul ID\nDriving license\nResidence permit',
		doctypeCount: 8,
	},
	{
		applicants: 26708,
		forgery: 24,
		percentageForgery: 0.0008986071589036993,
		id: 'BF',
		name: 'Burkina Faso',
		conversion: 97.92,
		measure: '%',
		doctype: 'Passport\nID card\n• Consular ID\n• Military ID\n• Professional ID\nDriving license',
		doctypeCount: 6,
	},
	{
		applicants: 252644,
		forgery: 3384,
		percentageForgery: 0.01339434144487896,
		id: 'BD',
		name: 'Bangladesh',
		conversion: 82.05,
		measure: '%',
		doctype: 'Passport\nID card\n• Disabled person ID\nDriving license',
		doctypeCount: 4,
	},
	{
		applicants: 125059,
		forgery: 246,
		percentageForgery: 0.0019670715422320665,
		id: 'BG',
		name: 'Bulgaria',
		conversion: 98.06,
		measure: '%',
		doctype:
			'Passport\n• Temporary Passport\nID card\n• Refugee ID\n• Card of Subsidiary Protection Beneficiary\nDriving license\nResidence permit',
		doctypeCount: 7,
	},
	{
		applicants: 28053,
		forgery: 39,
		percentageForgery: 0.001390225644316116,
		id: 'BH',
		name: 'Bahrain',
		conversion: 97.42,
		measure: '%',
		doctype: 'Passport\n• Diplomatic Passport\n• Special Passport\nID card\nDriving license',
		doctypeCount: 5,
	},
	{
		applicants: 3057,
		forgery: 43,
		percentageForgery: 0.014066077854105331,
		id: 'BS',
		name: 'Bahamas',
		conversion: 85.67,
		measure: '%',
		doctype: 'Passport\nVoter card\nDriving license\nResidence permit\n• Resident spouse permit\n• Work permit',
		doctypeCount: 6,
	},
	{
		applicants: 10116,
		forgery: 40,
		percentageForgery: 0.0039541320680110716,
		id: 'BA',
		name: 'Bosnia and Herzegovina',
		conversion: 97.87,
		measure: '%',
		doctype: 'Passport\nID card\nDriving license\nResidence permit',
		doctypeCount: 4,
	},
	{
		applicants: 71,
		forgery: 0,
		percentageForgery: 0,
		id: 'BL',
		name: 'Saint Barthelemy',
		conversion: 84.37,
		measure: '%',
		doctype: 'Passport\nID card\nDriving license',
		doctypeCount: 3,
	},
	{
		applicants: 276984,
		forgery: 515,
		percentageForgery: 0.001859313173324091,
		id: 'BY',
		name: 'Belarus',
		conversion: 97.92,
		measure: '%',
		doctype: 'Passport\nID card\n• Army / Military ID Card\nDriving license\nResidence permit',
		doctypeCount: 5,
	},
	{
		applicants: 444,
		forgery: 2,
		percentageForgery: 0.0045045045045045045,
		id: 'BZ',
		name: 'Belize',
		conversion: 84.62,
		measure: '%',
		doctype: 'Passport\nID card\nDriving license',
		doctypeCount: 3,
	},
	{
		applicants: 5686,
		forgery: 10,
		percentageForgery: 0.0017587055926837848,
		id: 'BM',
		name: 'Bermuda',
		conversion: 84.62,
		measure: '%',
		doctype: 'Passport\nID card\n• Special person card\n• Seniors ID card\n• Voter ID\nDriving license',
		doctypeCount: 6,
	},
	{
		applicants: 17196,
		forgery: 17,
		percentageForgery: 0.0009886020004652245,
		id: 'BO',
		name: 'Bolivia',
		conversion: 98.47,
		measure: '%',
		doctype: 'Passport\nID card\n• Military ID\nDriving license\nResidence permit',
		doctypeCount: 5,
	},
	{
		applicants: 2274608,
		forgery: 2607,
		percentageForgery: 0.0011461315532170818,
		id: 'BR',
		name: 'Brazil',
		conversion: 90.98,
		measure: '%',
		doctype:
			'Passport\nID card\n• Civil Aviation Agency Card\n• Carteira Especial De Identidade\n• Army / Military ID Card\n• Labor card\n• Military Service Exemption Certificate\n• Federal Council of Administration card\n• Federal Council of Physical Education card\n• Federal Nursing Council card\n• Federal Council of Engineering and agronomy card\n• Federal Council of Pharmacy card\n• Federal Council of Medicine card\n• Federal Council of Veterinary Medicine\n• Federal and Regional Council of Dentistry card\n• Regional Council Economy card\n• Regional Accounting Council card\n• Regional Council of Economics card\n• Regional Council of Psychology card\n• Council of Architecture and Urbanism of Brazil card\n• Consul ID\n• Functional identity card\n• Ministry of Defence cards\n• Ministry of Justice card\n• Refugee ID\n• Bar Association of Brazil card\n• Military Police card\n• Secretariat of Social Defense card\n• Secretary of State of Seguaranca Publica card\n• COFECI CRECI system card\nDriving license\n• Circulação Internacional de Automotores\n• Carteira de Habilitação do Amador\nResidence permit\n• Alien identity card',
		doctypeCount: 35,
	},
	{
		applicants: 1215,
		forgery: 10,
		percentageForgery: 0.00823045267489712,
		id: 'BB',
		name: 'Barbados',
		conversion: 87.02,
		measure: '%',
		doctype: 'Passport\nID card\nDriving license',
		doctypeCount: 3,
	},
	{
		applicants: 4108,
		forgery: 5,
		percentageForgery: 0.0012171372930866603,
		id: 'BN',
		name: 'Brunei Darussalam',
		conversion: 78.42,
		measure: '%',
		doctype: 'Passport\n• General Certificate of Identity\nID card\n• Military ID\nDriving license\nResidence permit',
		doctypeCount: 6,
	},
	{
		applicants: 862,
		forgery: 3,
		percentageForgery: 0.0034802784222737818,
		id: 'BT',
		name: 'Bhutan',
		conversion: 77.37,
		measure: '%',
		doctype: 'Passport\nID card\n• Voter ID\n• Citizenship Card\nDriving license',
		doctypeCount: 5,
	},
	{
		applicants: 14,
		forgery: 0,
		percentageForgery: 0,
		id: 'BV',
		name: 'Bouvet Island',
		conversion: 84.42,
		measure: '%',
		doctype: '',
		doctypeCount: 0,
	},
	{
		applicants: 12378,
		forgery: 67,
		percentageForgery: 0.005412829213120052,
		id: 'BW',
		name: 'Botswana',
		conversion: 94.22,
		measure: '%',
		doctype: 'Passport\nID card\nDriving license\nResidence permit',
		doctypeCount: 4,
	},
	{
		applicants: 203,
		forgery: 2,
		percentageForgery: 0.009852216748768473,
		id: 'CF',
		name: 'Central African Republic',
		conversion: 74.72,
		measure: '%',
		doctype: 'Passport\nDriving license\nResidence permit',
		doctypeCount: 3,
	},
	{
		applicants: 489625,
		forgery: 2007,
		percentageForgery: 0.004099055399540465,
		id: 'CA',
		name: 'Canada',
		conversion: 94.59,
		measure: '%',
		doctype:
			'Passport\n• Temporary Passport\n• Aviation Document\nID card\n• Firearms license\n• Military ID\n• Metis nation\n• Diplomatic ID\n• Health ID Card\n• Certificate of Indian status\n• Сertificate of Canadian Citizenship \n• Alberta ID card\n• British Columbia ID card\n• Manitoba ID card\n• New Brunswick ID card\n• Newfoundland and Labrador ID card\n• Northwest territories ID card\n• Nova Scotia ID card\n• Nunavut ID card\n• Ontario ID card\n• Prince Edward Island ID card\n• Quebec ID card\n• Saskatchewan ID card\n• Yukon ID card\nDriving license\n• Alberta DL\n• British Columbia DL\n• Brunswick DL\n• Manitoba DL\n• National Defence DL\n• Newfoundland and Labrador DL\n• Northwest DL\n• Nova Scotia DL\n• Nunavut DL\n• Ontario DL\n• Prince Edward Island DL\n• Quebec DL\n• Saskatchewan DL\n• Yukon DL\nResidence permit\n• Refugee ID',
		doctypeCount: 41,
	},
	{
		applicants: 13,
		forgery: 0,
		percentageForgery: 0,
		id: 'CC',
		name: 'Cocos (Keeling) Islands',
		conversion: 84.37,
		measure: '%',
		doctype: '',
		doctypeCount: 0,
	},
	{
		applicants: 83010,
		forgery: 173,
		percentageForgery: 0.0020840862546681123,
		id: 'CH',
		name: 'Switzerland',
		conversion: 97.41,
		measure: '%',
		doctype:
			'Passport\n• Refugee document\nID card\n• Diplomatic ID\nDriving license\n• Learner’s Permit\nResidence permit',
		doctypeCount: 7,
	},
	{
		applicants: 115989,
		forgery: 113,
		percentageForgery: 0.0009742303149436585,
		id: 'CL',
		name: 'Chile',
		conversion: 93.57,
		measure: '%',
		doctype: 'Passport\n• Emergency Passport\nID card\nResidence permit',
		doctypeCount: 4,
	},
	{
		applicants: 202091,
		forgery: 582,
		percentageForgery: 0.0028798907422893645,
		id: 'CN',
		name: 'China',
		conversion: 95.3,
		measure: '%',
		doctype:
			'Passport\nID card\n• Ethnic minorities ID:\n - Korean\n - Mongolian\n - Nuosu Yi\n - Tibetan\n - Uyghur\n - Zhuang\nDriving license\nResidence permit\n• Mainland Travel Permit for Hong Kong and Macao citizens\n• Shenzhen Special Economic Zone Residence permit\n• Zhejiang Province Residence permit\n• Hong Kong Macao pass\n• Taiwan Road Trip Permit\n• Taiwan pass\n• Mainland Travel Permit for Taiwan Residents\n• Beijing Tong Residence permit of Beijing\n• Wuxi Residence permit\n• Taiyuan Residence permit\n• Sticker Permit\n• Shenzhen Residence permit\n• Shanghai Residence permit \n• Residence permit for Taiwan Residents\n• Jiangsu Residence permit\n• Guangdong Residence permit\n• Fujian Residence permit',
		doctypeCount: 28,
	},
	{
		applicants: 32081,
		forgery: 227,
		percentageForgery: 0.0070758392818178984,
		id: 'CI',
		name: "Cote D'Ivoire",
		conversion: 92.78,
		measure: '%',
		doctype:
			"Passport\n• Diplomatic Passport\nID card\n• Carte d’assuré\n• Carte D'Identite Scolaire\n• Attestation d'Identite\n• Voter ID\n• Consul ID\nDriving license\nResidence permit",
		doctypeCount: 10,
	},
	{
		applicants: 46317,
		forgery: 309,
		percentageForgery: 0.006671416542522184,
		id: 'CM',
		name: 'Cameroon',
		conversion: 91.97,
		measure: '%',
		doctype:
			'Passport\n• African Union Passport\nID card\n• Consul ID\n• Temporary ID\n• Voter ID\nDriving license\nResidence permit',
		doctypeCount: 8,
	},
	{
		applicants: 3257,
		forgery: 56,
		percentageForgery: 0.017193736567393307,
		id: 'CD',
		name: 'Democratic Republic of the Congo',
		conversion: 77.42,
		measure: '%',
		doctype: 'Passport\n• Laissez Passer\nConsul ID \nVoter ID \nDriving license',
		doctypeCount: 5,
	},
	{
		applicants: 2424,
		forgery: 20,
		percentageForgery: 0.00825082508250825,
		id: 'CG',
		name: 'Republic of the Congo',
		conversion: 77.17,
		measure: '%',
		doctype: "Passport\nID card\n• Consul ID\n• Numero d'identification unique\nDriving license\nResidence permit",
		doctypeCount: 5,
	},
	{
		applicants: 41,
		forgery: 0,
		percentageForgery: 0,
		id: 'CK',
		name: 'Cook Islands',
		conversion: 84.42,
		measure: '%',
		doctype: 'Passport\nDriving license',
		doctypeCount: 2,
	},
	{
		applicants: 489212,
		forgery: 670,
		percentageForgery: 0.0013695493978070857,
		id: 'CO',
		name: 'Colombia',
		conversion: 91.32,
		measure: '%',
		doctype:
			'Passport\nID card\n• Consul ID\n• Permiso Especial de Permanencia\n• Refugee ID \nDriving license\nResidence permit',
		doctypeCount: 7,
	},
	{
		applicants: 334,
		forgery: 3,
		percentageForgery: 0.008982035928143712,
		id: 'KM',
		name: 'Comoros',
		conversion: 75.32,
		measure: '%',
		doctype: 'Passport\n• Diplomatic Passport\nID card\nDriving license',
		doctypeCount: 4,
	},
	{
		applicants: 645,
		forgery: 1,
		percentageForgery: 0.0015503875968992248,
		id: 'CV',
		name: 'Cape Verde',
		conversion: 85.92,
		measure: '%',
		doctype: 'Passport\nID card\nDriving license',
		doctypeCount: 3,
	},
	{
		applicants: 12049,
		forgery: 49,
		percentageForgery: 0.00406672752925554,
		id: 'CR',
		name: 'Costa Rica',
		conversion: 94.66,
		measure: '%',
		doctype: 'Passport\nID card\nDriving license\nResidence permit\n• Work permit',
		doctypeCount: 5,
	},
	{
		applicants: 9663,
		forgery: 46,
		percentageForgery: 0.004760426368622581,
		id: 'CU',
		name: 'Cuba',
		conversion: 87.57,
		measure: '%',
		doctype: 'Passport\nID card\nDriving license\nResidence permit',
		doctypeCount: 4,
	},
	{
		applicants: 0,
		forgery: 0,
		percentageForgery: 0,
		id: 'CW',
		name: 'Curaçao',
		conversion: 84.87,
		measure: '%',
		doctype: 'Passport\nID card\nDriving license',
		doctypeCount: 3,
	},
	{
		applicants: 19,
		forgery: 0,
		percentageForgery: 0,
		id: 'CX',
		name: 'Christmas Island',
		conversion: 0,
		measure: '%',
		doctype: '',
		doctypeCount: 0,
	},
	{
		applicants: 2683,
		forgery: 1,
		percentageForgery: 0.0003727171077152441,
		id: 'KY',
		name: 'Cayman Islands',
		conversion: 84.62,
		measure: '%',
		doctype: 'Passport\nDriving license',
		doctypeCount: 2,
	},
	{
		applicants: 42752,
		forgery: 84,
		percentageForgery: 0.001964820359281437,
		id: 'CY',
		name: 'Cyprus',
		conversion: 98.98,
		measure: '%',
		doctype: 'Passport\nID card\nDriving license\nResidence permit',
		doctypeCount: 4,
	},
	{
		applicants: 174613,
		forgery: 406,
		percentageForgery: 0.0023251418851975513,
		id: 'CZ',
		name: 'Czech Republic',
		conversion: 98.73,
		measure: '%',
		doctype:
			'Passport\n• Cestovni prukaz totoznosti\nID card\n• Diplomatic ID\n• Disabled person ID\n• Refugee ID\nDriving license\nResidence permit',
		doctypeCount: 8,
	},
	{
		applicants: 346465,
		forgery: 1201,
		percentageForgery: 0.0034664396115047695,
		id: 'DE',
		name: 'Germany',
		conversion: 98.09,
		measure: '%',
		doctype:
			'Passport\n• Reisepass\n• Passersatz\n• Reisausweis (Travel document)\nID card\n• Temporary ID\n• Diplomatic ID\n• Asylum ID\nDriving license\nResidence permit\n• Toleration Status card',
		doctypeCount: 11,
	},
	{
		applicants: 608,
		forgery: 8,
		percentageForgery: 0.013157894736842105,
		id: 'DJ',
		name: 'Djibouti',
		conversion: 74.72,
		measure: '%',
		doctype: 'Passport\nID card\nDriving license\nResidence permit',
		doctypeCount: 4,
	},
	{
		applicants: 1038,
		forgery: 7,
		percentageForgery: 0.00674373795761079,
		id: 'DM',
		name: 'Dominica',
		conversion: 85.62,
		measure: '%',
		doctype: 'Passport\nMulti-purpose ID card\nDriving license',
		doctypeCount: 3,
	},
	{
		applicants: 67725,
		forgery: 90,
		percentageForgery: 0.00132890365448505,
		id: 'DK',
		name: 'Denmark',
		conversion: 95.07,
		measure: '%',
		doctype:
			'Passport\nID cards (no National ID Card):\n• Army / Military ID card\n• Legitimationskort\nDriving license \nResidence permit',
		doctypeCount: 6,
	},
	{
		applicants: 42968,
		forgery: 186,
		percentageForgery: 0.004328802830013033,
		id: 'DO',
		name: 'Dominican Republic',
		conversion: 97.83,
		measure: '%',
		doctype: 'Passport\nID card\n• Voter card\n• Consul ID\nDriving license\nResidence permit\n• RT-9 card',
		doctypeCount: 7,
	},
	{
		applicants: 25415,
		forgery: 184,
		percentageForgery: 0.007239819004524887,
		id: 'DZ',
		name: 'Algeria',
		conversion: 93.41,
		measure: '%',
		doctype: 'Passport \nID card\n• Military ID\n• Carte d’Immatriculation\nDriving license',
		doctypeCount: 5,
	},
	{
		applicants: 27686,
		forgery: 146,
		percentageForgery: 0.005273423390883479,
		id: 'EC',
		name: 'Ecuador',
		conversion: 93.7,
		measure: '%',
		doctype: 'Passport\nID card\n• Consul ID\nDriving license\nResidence permit',
		doctypeCount: 5,
	},
	{
		applicants: 185120,
		forgery: 1180,
		percentageForgery: 0.006374243733794295,
		id: 'EG',
		name: 'Egypt',
		conversion: 61.83,
		measure: '%',
		doctype:
			'Passport\n• Travel Document for Palestinian Refugees\nID card (please contact us)\nDriving license(in some cases, notarized translation is required)\n• Pilot license\nResidence permit',
		doctypeCount: 6,
	},
	{
		applicants: 178,
		forgery: 0,
		percentageForgery: 0,
		id: 'ER',
		name: 'Eritrea',
		conversion: 61.83,
		measure: '%',
		doctype: 'Passport',
		doctypeCount: 1,
	},
	{
		applicants: 74,
		forgery: 1,
		percentageForgery: 0.013513513513513514,
		id: 'EH',
		name: 'Western Sahara',
		conversion: 74.77,
		measure: '%',
		doctype: '',
		doctypeCount: 0,
	},
	{
		applicants: 274369,
		forgery: 1272,
		percentageForgery: 0.004636092269899296,
		id: 'ES',
		name: 'Spain',
		conversion: 97.14,
		measure: '%',
		doctype:
			'Passport\nID card\n• Diplomatic ID\nDriving license\n• Guardia Civil license\nResidence permit\n• Asylum Seeker ID',
		doctypeCount: 7,
	},
	{
		applicants: 52472,
		forgery: 204,
		percentageForgery: 0.0038877877725262996,
		id: 'EE',
		name: 'Estonia',
		conversion: 97.96,
		measure: '%',
		doctype: "Passport\n• Alien's passport\nID card\nDriving license\nResidence permit",
		doctypeCount: 5,
	},
	{
		applicants: 2532,
		forgery: 17,
		percentageForgery: 0.006714060031595577,
		id: 'ET',
		name: 'Ethiopia',
		conversion: 51.58,
		measure: '%',
		doctype:
			'Passport\nID cards: \n• Tax ID\n• Kebele ID\n• Foreign Nationals of Ethiopian Origin ID \n• Addis Ababa City Resident ID Card \nDriving license (in some cases, notarized translation is required)',
		doctypeCount: 7,
	},
	{
		applicants: 76084,
		forgery: 169,
		percentageForgery: 0.0022212291677619475,
		id: 'FI',
		name: 'Finland',
		conversion: 98.26,
		measure: '%',
		doctype:
			"Passport\n• Diplomatic Passport\nID card\n• Minor's ID\nDriving license\n• Pahvinen Ajokortti (Cardboard license)\nResidence permit",
		doctypeCount: 7,
	},
	{
		applicants: 946,
		forgery: 4,
		percentageForgery: 0.004228329809725159,
		id: 'FJ',
		name: 'Fiji',
		conversion: 85.72,
		measure: '%',
		doctype: 'Passport\nVoter card\nDriving license\n• Provisional',
		doctypeCount: 4,
	},
	{
		applicants: 18,
		forgery: 0,
		percentageForgery: 0,
		id: 'FK',
		name: 'Falkland Islands (Malvinas)',
		conversion: 0,
		measure: '%',
		doctype: '',
		doctypeCount: 0,
	},
	{
		applicants: 766696,
		forgery: 3641,
		percentageForgery: 0.004748948735874454,
		id: 'FR',
		name: 'France',
		conversion: 96.39,
		measure: '%',
		doctype:
			"Passport\n• Emergency Passport\n• Travel Document for Refugee\n• Diplomatic Passport\n• Service Passport\nID card\n• Army / Military ID\n• Diplomatic ID\n• Carte Individuelle d'Admission a l'Aide Médicale de l'Etat\n• Gendarmerie Nationale\nDriving license\nResidence permit\n• DCEM Minor Permit\n• Récépissé (Renewal Receipt)\n• Attestation de Demande d'Asile\n• Récépissé Constatant la Reconnaissance Dune Protection Internationale\n• Autorisation Provisoire de Sejour",
		doctypeCount: 17,
	},
	{
		applicants: 358,
		forgery: 2,
		percentageForgery: 0.00558659217877095,
		id: 'FO',
		name: 'Faroe Islands',
		conversion: 84.82,
		measure: '%',
		doctype: 'Driving license',
		doctypeCount: 1,
	},
	{
		applicants: 70,
		forgery: 0,
		percentageForgery: 0,
		id: 'FM',
		name: 'Micronesia',
		conversion: 84.42,
		measure: '%',
		doctype: '',
		doctypeCount: 0,
	},
	{
		applicants: 2284,
		forgery: 13,
		percentageForgery: 0.005691768826619965,
		id: 'GA',
		name: 'Gabon',
		conversion: 77.32,
		measure: '%',
		doctype:
			"Passport\nID card\n• Consul ID\n• Demande de Carte Nationale D'Identite\nDriving license\nResidence permit",
		doctypeCount: 6,
	},
	{
		applicants: 658147,
		forgery: 2549,
		percentageForgery: 0.0038729949388206586,
		id: 'GB',
		name: 'United Kingdom',
		conversion: 95.86,
		measure: '%',
		doctype:
			'Passport\n• Travel Document\n• Emergency Passport\n• British Overseas Territories Passport\nID card - no National ID\n• Citizencard, Totum ID, Young Scot\n• Electoral ID\nDriving license\n• Provisional\n• Welsh (Cymraeg)\n• Brexit design\n• Northern Ireland design\nResidence permit',
		doctypeCount: 13,
	},
	{
		applicants: 32152,
		forgery: 135,
		percentageForgery: 0.004198805673052999,
		id: 'GE',
		name: 'Georgia',
		conversion: 96.73,
		measure: '%',
		doctype: 'Passport\nID card\nDriving license\nResidence permit\n• Temporary Residence permit card',
		doctypeCount: 5,
	},
	{
		applicants: 647,
		forgery: 0,
		percentageForgery: 0,
		id: 'GG',
		name: 'Guernsey',
		conversion: 84.47,
		measure: '%',
		doctype: 'Passport\nDriving license',
		doctypeCount: 2,
	},
	{
		applicants: 45335,
		forgery: 679,
		percentageForgery: 0.014977390537112606,
		id: 'GH',
		name: 'Ghana',
		conversion: 89.93,
		measure: '%',
		doctype:
			'Passport\nID card\n• Dual Citizenship ID card\n• National Health\n• Refugee ID\n• Social ID\n• Consular ID\n• ECOWAS ID\n• Voter ID\n• Non-Citizen identity card\nDriving license\n• Temporary',
		doctypeCount: 13,
	},
	{
		applicants: 1050,
		forgery: 2,
		percentageForgery: 0.0019047619047619048,
		id: 'GI',
		name: 'Gibraltar',
		conversion: 84.87,
		measure: '%',
		doctype: 'Passport\n• Emergency Passport\nID card\n• Civilian Registration card\nDriving license',
		doctypeCount: 4,
	},
	{
		applicants: 1870,
		forgery: 9,
		percentageForgery: 0.004812834224598931,
		id: 'GN',
		name: 'Guinea',
		conversion: 75.87,
		measure: '%',
		doctype: 'Passport\nID card\n• Voter ID\n• Consul ID\n• ECOWAS ID\nDriving license',
		doctypeCount: 6,
	},
	{
		applicants: 927,
		forgery: 8,
		percentageForgery: 0.008629989212513484,
		id: 'GP',
		name: 'Guadeloupe',
		conversion: 84.47,
		measure: '%',
		doctype: 'Passport\nID card',
		doctypeCount: 2,
	},
	{
		applicants: 669,
		forgery: 6,
		percentageForgery: 0.008968609865470852,
		id: 'GM',
		name: 'Gambia',
		conversion: 75.62,
		measure: '%',
		doctype: 'Passport\nID card\n• Voter card\n• ECOWAS ID\nDriving license\nResidence permit',
		doctypeCount: 6,
	},
	{
		applicants: 107,
		forgery: 2,
		percentageForgery: 0.018691588785046728,
		id: 'GW',
		name: 'Guinea-Bissau',
		conversion: 74.82,
		measure: '%',
		doctype: 'Passport\nID card\n• ECOWAS ID\nDriving license',
		doctypeCount: 4,
	},
	{
		applicants: 351,
		forgery: 1,
		percentageForgery: 0.002849002849002849,
		id: 'GQ',
		name: 'Equatorial Guinea',
		conversion: 84.62,
		measure: '%',
		doctype: 'Passport\nID card\nDriving license\nResidence permit',
		doctypeCount: 4,
	},
	{
		applicants: 217411,
		forgery: 418,
		percentageForgery: 0.0019226258101016048,
		id: 'GR',
		name: 'Greece',
		conversion: 92.95,
		measure: '%',
		doctype:
			'Passport\n• Service Passport\n• Diplomatic Passport\nID card\n• Army / Military ID Card\n• Air force ID\n• Marine ID\n• Fire corps ID\n• National defence ID\n• Refugee ID\n• International Protection Applicant Card\nDriving license\nResidence permit',
		doctypeCount: 13,
	},
	{
		applicants: 425,
		forgery: 4,
		percentageForgery: 0.009411764705882352,
		id: 'GD',
		name: 'Grenada',
		conversion: 84.82,
		measure: '%',
		doctype: 'Passport\nNational Insurance card\nVoter ID\nDriving license',
		doctypeCount: 4,
	},
	{
		applicants: 179,
		forgery: 0,
		percentageForgery: 0,
		id: 'GL',
		name: 'Greenland',
		conversion: 95.07,
		measure: '%',
		doctype: 'Passport\nDriving license',
		doctypeCount: 2,
	},
	{
		applicants: 10302,
		forgery: 24,
		percentageForgery: 0.0023296447291788003,
		id: 'GT',
		name: 'Guatemala',
		conversion: 99.52,
		measure: '%',
		doctype: 'Passport\nID card\n• Consular ID\nDriving license',
		doctypeCount: 4,
	},
	{
		applicants: 498,
		forgery: 5,
		percentageForgery: 0.010040160642570281,
		id: 'GF',
		name: 'French Guiana',
		conversion: 84.37,
		measure: '%',
		doctype: 'Passport\nID card',
		doctypeCount: 2,
	},
	{
		applicants: 666,
		forgery: 4,
		percentageForgery: 0.006006006006006006,
		id: 'GU',
		name: 'Guam',
		conversion: 84.52,
		measure: '%',
		doctype: 'ID card\nDriving license',
		doctypeCount: 2,
	},
	{
		applicants: 1299,
		forgery: 10,
		percentageForgery: 0.007698229407236336,
		id: 'GY',
		name: 'Guyana',
		conversion: 76.27,
		measure: '%',
		doctype: 'Passport\nID card\nDriving license',
		doctypeCount: 3,
	},
	{
		applicants: 41172,
		forgery: 302,
		percentageForgery: 0.007335082094627417,
		id: 'HK',
		name: 'Hong Kong',
		conversion: 97.89,
		measure: '%',
		doctype: 'Passport\nID card\n• Consular Corps ID card',
		doctypeCount: 4,
	},
	{
		applicants: 18,
		forgery: 0,
		percentageForgery: 0,
		id: 'HM',
		name: 'Heard Island & Mcdonald Islands',
		conversion: 84.37,
		measure: '%',
		doctype: '',
		doctypeCount: 0,
	},
	{
		applicants: 4934,
		forgery: 26,
		percentageForgery: 0.00526955816781516,
		id: 'HN',
		name: 'Honduras',
		conversion: 92.06,
		measure: '%',
		doctype: 'Passport\nID card\n• Consul ID\nDriving license\nResidence permit',
		doctypeCount: 5,
	},
	{
		applicants: 90119,
		forgery: 103,
		percentageForgery: 0.0011429332327256183,
		id: 'HR',
		name: 'Croatia',
		conversion: 98.86,
		measure: '%',
		doctype: 'Passport\nID card\nDriving license\nResidence permit',
		doctypeCount: 4,
	},
	{
		applicants: 4292,
		forgery: 26,
		percentageForgery: 0.0060577819198508855,
		id: 'HT',
		name: 'Haiti',
		conversion: 87.92,
		measure: '%',
		doctype: 'Passport\nID card\nDriving license',
		doctypeCount: 3,
	},
	{
		applicants: 143106,
		forgery: 182,
		percentageForgery: 0.0012717845513116153,
		id: 'HU',
		name: 'Hungary',
		conversion: 98.12,
		measure: '%',
		doctype:
			'Passport\nID card\n• Booklet ID\n• Temporary\nDriving license\nResidence permit\n• Kishatarforgalmi Engedely\n• Foreigner ID',
		doctypeCount: 8,
	},
	{
		applicants: 587559,
		forgery: 2326,
		percentageForgery: 0.0039587513764575135,
		id: 'ID',
		name: 'Indonesia',
		conversion: 87.57,
		measure: '%',
		doctype:
			'Passport\n• Service Passport\n• Diplomatic Passport\nKartu Tanda Penduduk (KTP)\n• Surat Keterangan\nDriving license\nResidence permit\n• Limited Stay Permit Card',
		doctypeCount: 8,
	},
	{
		applicants: 629,
		forgery: 0,
		percentageForgery: 0,
		id: 'IM',
		name: 'Isle of Man',
		conversion: 89.43,
		measure: '%',
		doctype: 'Passport\nDriving license',
		doctypeCount: 2,
	},
	{
		applicants: 2249176,
		forgery: 5387,
		percentageForgery: 0.0023950993608325894,
		id: 'IN',
		name: 'India',
		conversion: 81.4,
		measure: '%',
		doctype:
			'Passport\n• Overseas Citizen of India Certificate of Registration\nID card (Aadhaar)\n• Aadhaar\n• Ex Servicemen ID card\n• Border Police Force ID\n• Indian Armed Forces Civilian card\n• Islanders Identity card (Andaman and Nicobar)\n• Permanent Account Number card\n• Post Office ID card\n• Resident Identity card\n• Tax ID\n• Voter ID\n• Ration card\n• e-SHRAM Card\nDriving license\n• Andhra State DL\n• Arunachal State DL\n• Assam State DL\n• Bihar State DL\n• Chandigarh State DL\n• Chhattisgarh State DL\n• Delhi state DL\n• Goa State DL\n• Gujarat State DL\n• Haryana State DL\n• Hoshiarpur State DL\n• Booklet DL\n• Indian Union DL\n• Jalandhar State DL\n• Jammu and Kashmir state DL\n• Jharkhand state DL\n• Karnataka state DL\n• Kerala state DL\n• Madhya state DL\n• Maharashtra state DL\n• Manipur state DL\n• Meghalaya state DL\n• Mizoram state DL\n• Nagaland state DL\n• Odisha (Orissa) state DL\n• Pondicherry (Puducherry) state DL\n• Punjab state DL\n• Rajasthan state DL\n• Sikkim state DL\n• Tamil Nadu state DL\n• Tripura state DL\n• Telangana state DL\n• Uttar state DL\n• West Bengal state DL\n• Central Motor Vehicles\n• Union of India DL\n• Uttarakhand DL',
		doctypeCount: 53,
	},
	{
		applicants: 57,
		forgery: 3,
		percentageForgery: 0.05263157894736842,
		id: 'IO',
		name: 'British Indian Ocean Territory',
		conversion: 84.42,
		measure: '%',
		doctype: '',
		doctypeCount: 0,
	},
	{
		applicants: 67934,
		forgery: 166,
		percentageForgery: 0.0024435481496746844,
		id: 'IE',
		name: 'Ireland',
		conversion: 96.54,
		measure: '%',
		doctype: 'Passport\n• Refugee document\nID card\n• Military ID\nDriving license\nResidence permit',
		doctypeCount: 6,
	},
	{
		applicants: 45980,
		forgery: 230,
		percentageForgery: 0.005002174858634189,
		id: 'IR',
		name: 'Iran',
		conversion: 79.79,
		measure: '%',
		doctype:
			'Passport\nID card (please contact us)\n• End-of-Service Smart card (please contact us)\n• Shenasnameh card (please contact us)\nDriving license (please contact us)\n• Motorcycle DL (please contact us)\nResidence permit (please contact us)\n• Refugee ID (please contact us)',
		doctypeCount: 8,
	},
	{
		applicants: 14933,
		forgery: 765,
		percentageForgery: 0.05122882207192125,
		id: 'IQ',
		name: 'Iraq',
		conversion: 84.27,
		measure: '%',
		doctype:
			'Passport\nID card\n• Booklet ID (non-Latin)\n• Voter ID\nDriving license\n• DL in form of plastic card (non-Latin)\n• DL in form of plastic card with MRZ\nResidence permit (in some cases, notarized translation is required)',
		doctypeCount: 8,
	},
	{
		applicants: 7158,
		forgery: 65,
		percentageForgery: 0.009080748812517463,
		id: 'IS',
		name: 'Iceland',
		conversion: 92.93,
		measure: '%',
		doctype: 'Passport\nID card\nDriving license\nResidence permit',
		doctypeCount: 4,
	},
	{
		applicants: 102815,
		forgery: 138,
		percentageForgery: 0.0013422166026358022,
		id: 'IL',
		name: 'Israel',
		conversion: 95.75,
		measure: '%',
		doctype:
			'Passport\n• Provisional Passport\nID card \n• Army / Military ID Card\n• Judea and Samaria state card\nDriving license\n• Operator’s (Skipper’s) certificate\nResidence permit (Conditional Release 2(a)5 visa, accepted only if the owner’s photo is present',
		doctypeCount: 8,
	},
	{
		applicants: 376105,
		forgery: 1277,
		percentageForgery: 0.0033953284322197257,
		id: 'IT',
		name: 'Italy',
		conversion: 96.21,
		measure: '%',
		doctype:
			'Passport\n• Travel document\nID card\n• Army / Military ID card\n• Diplomatic ID\n• Booklet ID\nDriving license\n• Booklet DL\nResidence permit\n• Booklet RP',
		doctypeCount: 10,
	},
	{
		applicants: 7139,
		forgery: 40,
		percentageForgery: 0.005603025633842275,
		id: 'JM',
		name: 'Jamaica',
		conversion: 91.24,
		measure: '%',
		doctype: 'Passport\nID cards:\n• Firearm Licence\n• Jamaica Defence force\n• Voter ID\nDriving license',
		doctypeCount: 6,
	},
	{
		applicants: 1245,
		forgery: 1,
		percentageForgery: 0.0008032128514056225,
		id: 'JE',
		name: 'Jersey',
		conversion: 85.17,
		measure: '%',
		doctype: 'Passport\nDriving license',
		doctypeCount: 2,
	},
	{
		applicants: 20783,
		forgery: 114,
		percentageForgery: 0.005485252369725256,
		id: 'JO',
		name: 'Jordan',
		conversion: 94.87,
		measure: '%',
		doctype:
			'Passport\nID card\n• Sons of Jordanian Women card\n• Gazan Refugee ID (non-Latin)\n• Syrian Community Refugee ID (non-Latin)\n• Military ID\n• Public Security Directorate\nDriving license\nResidence permit\n• RP for Citizens of Arabic countries (non-Latin)\n• Work Permit',
		doctypeCount: 11,
	},
	{
		applicants: 245457,
		forgery: 387,
		percentageForgery: 0.0015766509001576652,
		id: 'JP',
		name: 'Japan',
		conversion: 96.46,
		measure: '%',
		doctype:
			'Passport\n• Re-entry permit\nID cards:\n• My Number Card\n• Ground Self-Defense Force Personnel card\n• Residential Land and Building Trader Certificate\nDriving license\n• Provisional Driving license\n• Voluntary Returned Driving license\nResidence permit\n• Zairyi card\n• Basic Resident Registration card',
		doctypeCount: 12,
	},
	{
		applicants: 451873,
		forgery: 518,
		percentageForgery: 0.0011463397901622801,
		id: 'KZ',
		name: 'Kazakhstan',
		conversion: 97.58,
		measure: '%',
		doctype:
			'Passport\n• Diplomatic Passport\n• Alien Passport\n• Service Passport\nID card\nDriving license\nResidence permit',
		doctypeCount: 7,
	},
	{
		applicants: 46263,
		forgery: 792,
		percentageForgery: 0.01711951235328448,
		id: 'KE',
		name: 'Kenya',
		conversion: 88.1,
		measure: '%',
		doctype:
			'Passport\n• East African Passport\nID card\n• Huduma Namba card\n• Military ID\n• Refugee ID\nDriving license\n• Booklet DL\nResidence permit',
		doctypeCount: 9,
	},
	{
		applicants: 116049,
		forgery: 111,
		percentageForgery: 0.0009564925160923403,
		id: 'KG',
		name: 'Kyrgyzstan',
		conversion: 98.57,
		measure: '%',
		doctype: 'Passport\nID card\n• Passport card\nDriving license',
		doctypeCount: 4,
	},
	{
		applicants: 54066,
		forgery: 51,
		percentageForgery: 0.0009432915325713017,
		id: 'KH',
		name: 'Cambodia',
		conversion: 92.65,
		measure: '%',
		doctype: 'Passport\n• Cambodia-Thailand Border Pass\nID card\nDriving license\nPermanent resident card',
		doctypeCount: 7,
	},
	{
		applicants: 155,
		forgery: 1,
		percentageForgery: 0.0064516129032258064,
		id: 'KI',
		name: 'Kiribati',
		conversion: 84.42,
		measure: '%',
		doctype: 'Passport\nID card\nDriving license',
		doctypeCount: 3,
	},
	{
		applicants: 701,
		forgery: 4,
		percentageForgery: 0.005706134094151213,
		id: 'KN',
		name: 'Saint Kitts and Nevis',
		conversion: 85.77,
		measure: '%',
		doctype: 'Passport\nID card\n• Social ID\nDriving license',
		doctypeCount: 4,
	},
	{
		applicants: 160843,
		forgery: 300,
		percentageForgery: 0.001865172870438875,
		id: 'KR',
		name: 'Korea',
		conversion: 91.07,
		measure: '%',
		doctype:
			'Passport\nID card \n• Minor\u2019s ID\n• Korean ID card\n• Welfare card\nDriving license\nResidence permit \n• Overseas Korean',
		doctypeCount: 8,
	},
	{
		applicants: 65671,
		forgery: 67,
		percentageForgery: 0.0010202372432276043,
		id: 'KW',
		name: 'Kuwait',
		conversion: 94.41,
		measure: '%',
		doctype: 'Passport\nID card\n• Stateless person card (please contact us)\nDriving license',
		doctypeCount: 4,
	},
	{
		applicants: 25578,
		forgery: 43,
		percentageForgery: 0.0016811322230041441,
		id: 'LA',
		name: 'Laos',
		conversion: 81.42,
		measure: '%',
		doctype: 'Passport\nID card (non-Latin)\nDriving license (non-Latin)',
		doctypeCount: 3,
	},
	{
		applicants: 10092,
		forgery: 54,
		percentageForgery: 0.00535077288941736,
		id: 'LB',
		name: 'Lebanon',
		conversion: 73.66,
		measure: '%',
		doctype:
			'Passport\nID card (non-Latin)\n• Consul ID\nDriving license\n• Laminated paper card (non-Latin)\nResidence permit (some may require notarized translation)',
		doctypeCount: 6,
	},
	{
		applicants: 597,
		forgery: 2,
		percentageForgery: 0.0033500837520938024,
		id: 'LR',
		name: 'Liberia',
		conversion: 74.82,
		measure: '%',
		doctype: 'Passport\nID card\n• Social ID\nDriving license',
		doctypeCount: 4,
	},
	{
		applicants: 2400,
		forgery: 47,
		percentageForgery: 0.019583333333333335,
		id: 'LY',
		name: 'Libya',
		conversion: 76.59,
		measure: '%',
		doctype:
			'Passport\nID card (non-Latin)\n• Civil Registry Authority card\nDriving license (non-Latin)\n• Booklet DL\n• First Grade DL (non-Latin)\n• Second Grade DL (non-Latin)',
		doctypeCount: 7,
	},
	{
		applicants: 796,
		forgery: 2,
		percentageForgery: 0.002512562814070352,
		id: 'LC',
		name: 'Saint Lucia',
		conversion: 84.92,
		measure: '%',
		doctype: 'Passport\nID card\nDriving license',
		doctypeCount: 3,
	},
	{
		applicants: 812,
		forgery: 4,
		percentageForgery: 0.0049261083743842365,
		id: 'LI',
		name: 'Liechtenstein',
		conversion: 89.33,
		measure: '%',
		doctype: 'Passport\nID card\nDriving license\nResidence permit',
		doctypeCount: 4,
	},
	{
		applicants: 26167,
		forgery: 145,
		percentageForgery: 0.005541330683685558,
		id: 'LK',
		name: 'Sri Lanka',
		conversion: 83.64,
		measure: '%',
		doctype:
			'Passport\nID card\n• Paper ID (translation required)\n• Military ID\n• Adult identity card\nDriving license\n• Learners Permit',
		doctypeCount: 5,
	},
	{
		applicants: 3445,
		forgery: 31,
		percentageForgery: 0.008998548621190131,
		id: 'LS',
		name: 'Lesotho',
		conversion: 75.77,
		measure: '%',
		doctype: 'Passport\nID card\n• Voter ID \nDriving license',
		doctypeCount: 4,
	},
	{
		applicants: 91938,
		forgery: 200,
		percentageForgery: 0.0021753790598011704,
		id: 'LT',
		name: 'Lithuania',
		conversion: 98.98,
		measure: '%',
		doctype: 'Passport\nID card\n• Refugee ID\nDriving license\nResidence permit',
		doctypeCount: 5,
	},
	{
		applicants: 12124,
		forgery: 18,
		percentageForgery: 0.0014846585285384361,
		id: 'LU',
		name: 'Luxembourg',
		conversion: 98.36,
		measure: '%',
		doctype: 'Passport\nID card\nDriving license \nResidence permit',
		doctypeCount: 4,
	},
	{
		applicants: 74716,
		forgery: 352,
		percentageForgery: 0.004711172974998661,
		id: 'LV',
		name: 'Latvia',
		conversion: 98.04,
		measure: '%',
		doctype: 'Passport\nID card\n• Latvijas Nepilsonis \nDriving license\n• Learner’s Permit\nResidence permit',
		doctypeCount: 6,
	},
	{
		applicants: 1544,
		forgery: 6,
		percentageForgery: 0.0038860103626943004,
		id: 'MO',
		name: 'Macao',
		conversion: 78.37,
		measure: '%',
		doctype: 'Passport\nID card\nDriving license\nResidence permit',
		doctypeCount: 0,
	},
	{
		applicants: 102,
		forgery: 0,
		percentageForgery: 0,
		id: 'MF',
		name: 'Saint Martin',
		conversion: 84.52,
		measure: '%',
		doctype: 'ID card\nDriving license',
		doctypeCount: 2,
	},
	{
		applicants: 275051,
		forgery: 369,
		percentageForgery: 0.001341569381678307,
		id: 'MA',
		name: 'Morocco',
		conversion: 93.32,
		measure: '%',
		doctype:
			'Passport\n• Diplomatic Passport\n• Special Passport\nID card\nDriving license\n• Provisoire DL\nResidence permit\n• Carte d’Immatriculation',
		doctypeCount: 8,
	},
	{
		applicants: 614,
		forgery: 2,
		percentageForgery: 0.003257328990228013,
		id: 'MC',
		name: 'Monaco',
		conversion: 89.38,
		measure: '%',
		doctype: 'Passport\nID card\nDriving license\nResidence permit\n• Carte de Sejour\n• Carte de Resident',
		doctypeCount: 6,
	},
	{
		applicants: 33387,
		forgery: 187,
		percentageForgery: 0.005600982418306527,
		id: 'MD',
		name: 'Moldova',
		conversion: 97.16,
		measure: '%',
		doctype: 'Passport\nID card\n• Stateless ID\nDriving license\n• Booklet DL\nResidence permit',
		doctypeCount: 6,
	},
	{
		applicants: 20047,
		forgery: 354,
		percentageForgery: 0.01765850251908016,
		id: 'MG',
		name: 'Madagascar',
		conversion: 90.97,
		measure: '%',
		doctype: 'Passport\nID card\nDriving license\n• DL in form of booklet\nResidence permit',
		doctypeCount: 5,
	},
	{
		applicants: 8131,
		forgery: 28,
		percentageForgery: 0.0034436108719714674,
		id: 'MV',
		name: 'Maldives',
		conversion: 91.8,
		measure: '%',
		doctype:
			'Passport\nID card\nDriving license\n• Probationary DL\n• Airline Transport Pilot Licence\nResidence permit\n• Work Visa card',
		doctypeCount: 7,
	},
	{
		applicants: 232676,
		forgery: 272,
		percentageForgery: 0.001169007546975193,
		id: 'MX',
		name: 'Mexico',
		conversion: 94.16,
		measure: '%',
		doctype:
			'Passport\nID cards:\n• Military ID\n• Consular ID\n• Secretary of Public Education card\n• Voter ID\nDriving license\n• Aguascalientes state DL\n• Baja California state DL\n• Baja California Sur state DL\n• Campeche state DL\n• Cancun DL\n• Chiapas state DL\n• Chihuahua state DL\n• Chihuahua (Chofer Particular)\n• Mexico city DL\n• Coahuila State DL\n• Colima state DL\n• Durango state DL\n• Federal DL\n• Guerrero state DL\n• Guanajuato state DL\n• Estado de Mexico\n• Hidalgo state DL\n• Jalisco state DL\n• Mexico state DL\n• Michoacan state DL\n• Morelos state DL\n• Nayarit state DL\n• Nuevo Leon state DL\n• Oaxaca state DL\n• Puebla state DL\n• Queretaro state DL\n• Quintana Roo state DL\n• San Luis Potosi state DL\n• Sinaloa state DL\n• Solidaridad state DL\n• Sonora state DL\n• Tabasco state DL\n• Tamaulipas state DL\n• Tlaxcala state DL\n• Tulum city DL\n• Veracruz state DL\n• Yucatan state DL\n• Zacatecas state DL\nResidence permit\n• Residente temporal card\n• Residente Permanente card',
		doctypeCount: 48,
	},
	{
		applicants: 65,
		forgery: 1,
		percentageForgery: 0.015384615384615385,
		id: 'MH',
		name: 'Marshall Islands',
		conversion: 0,
		measure: '%',
		doctype: 'Passport\nID card \nDriving license',
		doctypeCount: 3,
	},
	{
		applicants: 9334,
		forgery: 22,
		percentageForgery: 0.0023569745018212985,
		id: 'MK',
		name: 'Macedonia',
		conversion: 95.78,
		measure: '%',
		doctype: 'Passport\nID card\nDriving license \nResidence permit',
		doctypeCount: 4,
	},
	{
		applicants: 4140,
		forgery: 17,
		percentageForgery: 0.004106280193236715,
		id: 'ML',
		name: 'Mali',
		conversion: 76.22,
		measure: '%',
		doctype: 'Passport\n• Diplomatic Passport\nID card\n• Booklet ID\n• Voter ID\n• Consul ID\nDriving license',
		doctypeCount: 7,
	},
	{
		applicants: 17815,
		forgery: 51,
		percentageForgery: 0.002862756104406399,
		id: 'MT',
		name: 'Malta',
		conversion: 98.44,
		measure: '%',
		doctype: 'Passport\nID card\n• Refugee ID\nDriving license\nResidence permit',
		doctypeCount: 5,
	},
	{
		applicants: 51346,
		forgery: 61,
		percentageForgery: 0.0011880185408795231,
		id: 'MM',
		name: 'Myanmar',
		conversion: 60.22,
		measure: '%',
		doctype:
			'Passport\nID card (non-Latin)\n• Overseas worker ID card\nDriving license\n• Paper card DL (non-Latin)\n• Hak Tiex Man Veng Ting Ra Daux (Hak Tiex Praog) Plah Voe Lai Pha Cag Law Li DL\n• Motor Driver\u2019s license certificate',
		doctypeCount: 8,
	},
	{
		applicants: 3146,
		forgery: 5,
		percentageForgery: 0.001589319771137953,
		id: 'ME',
		name: 'Montenegro',
		conversion: 98.46,
		measure: '%',
		doctype: 'Passport\nID card\nDriving license\nResidence permit',
		doctypeCount: 4,
	},
	{
		applicants: 9776,
		forgery: 52,
		percentageForgery: 0.005319148936170213,
		id: 'MN',
		name: 'Mongolia',
		conversion: 94.57,
		measure: '%',
		doctype: 'Passport\nID card\nDriving license\nResidence permit',
		doctypeCount: 4,
	},
	{
		applicants: 172,
		forgery: 2,
		percentageForgery: 0.011627906976744186,
		id: 'MP',
		name: 'Northern Mariana Islands',
		conversion: 84.37,
		measure: '%',
		doctype: 'Passport\nID Card\n• Saipan ID\n• Tinian ID\nDriving license',
		doctypeCount: 5,
	},
	{
		applicants: 5259,
		forgery: 46,
		percentageForgery: 0.008746910058946568,
		id: 'MZ',
		name: 'Mozambique',
		conversion: 92.09,
		measure: '%',
		doctype:
			'Passport\n• Travel document\nID card\n• Recibo de Espera slip \n• Refugee ID\n• Voter ID \nDriving license\nResidence permit',
		doctypeCount: 8,
	},
	{
		applicants: 872,
		forgery: 6,
		percentageForgery: 0.006880733944954129,
		id: 'MR',
		name: 'Mauritania',
		conversion: 76.37,
		measure: '%',
		doctype: 'Passport\nID card\nDriving license \nResidence permit',
		doctypeCount: 4,
	},
	{
		applicants: 30,
		forgery: 1,
		percentageForgery: 0.03333333333333333,
		id: 'MS',
		name: 'Montserrat',
		conversion: 84.37,
		measure: '%',
		doctype: 'Passport\nDriving license',
		doctypeCount: 2,
	},
	{
		applicants: 899,
		forgery: 17,
		percentageForgery: 0.018909899888765295,
		id: 'MQ',
		name: 'Martinique',
		conversion: 84.37,
		measure: '%',
		doctype: 'Passport\nID card\nDriving license',
		doctypeCount: 3,
	},
	{
		applicants: 3563,
		forgery: 13,
		percentageForgery: 0.003648610721302273,
		id: 'MU',
		name: 'Mauritius',
		conversion: 79.37,
		measure: '%',
		doctype: 'Passport\nID card\nDriving license',
		doctypeCount: 3,
	},
	{
		applicants: 1392,
		forgery: 30,
		percentageForgery: 0.021551724137931036,
		id: 'MW',
		name: 'Malawi',
		conversion: 75.92,
		measure: '%',
		doctype: 'Passport\nID card\nDriving license',
		doctypeCount: 3,
	},
	{
		applicants: 191750,
		forgery: 372,
		percentageForgery: 0.001940026075619296,
		id: 'MY',
		name: 'Malaysia',
		conversion: 96.59,
		measure: '%',
		doctype:
			'Passport\nMyKAD Card\n• MyKAS card\n• MyKAD\n• Military ID\nDriving license\n• Learner’s DL , should be accompanied by expiry date slip\n• Vocational license\nResidence permit\n• Student Pass\n• Work Permit Service card',
		doctypeCount: 11,
	},
	{
		applicants: 146,
		forgery: 2,
		percentageForgery: 0.0136986301369863,
		id: 'YT',
		name: 'Mayotte',
		conversion: 0,
		measure: '%',
		doctype: 'Passport\nID card',
		doctypeCount: 2,
	},
	{
		applicants: 24651,
		forgery: 254,
		percentageForgery: 0.010303841629142834,
		id: 'NA',
		name: 'Namibia',
		conversion: 78.42,
		measure: '%',
		doctype: 'Passport\nID card\n• Refugee ID\n• Voter ID\nResidence permit',
		doctypeCount: 5,
	},
	{
		applicants: 204,
		forgery: 0,
		percentageForgery: 0,
		id: 'NC',
		name: 'New Caledonia',
		conversion: 67.21,
		measure: '%',
		doctype: 'Passport\nID card',
		doctypeCount: 2,
	},
	{
		applicants: 2382,
		forgery: 16,
		percentageForgery: 0.006717044500419815,
		id: 'NE',
		name: 'Niger',
		conversion: 75.82,
		measure: '%',
		doctype: 'Passport\nID card\n• Consul ID\n• Voter ID\nDriving license\n• DL in form of booklet',
		doctypeCount: 6,
	},
	{
		applicants: 36,
		forgery: 0,
		percentageForgery: 0,
		id: 'NF',
		name: 'Norfolk Island',
		doctype: '',
		doctypeCount: 0,
	},
	{
		applicants: 1555010,
		forgery: 16700,
		percentageForgery: 0.010739480775043247,
		id: 'NG',
		name: 'Nigeria',
		conversion: 67.21,
		measure: '%',
		doctype:
			'Passport\nID card (Mastercard)\n• National Identification Number Slip (NINs) in form of plastic card\n• National Identification Number Slip (NINs) in form of paper slip (doesn’t have DoB on it, not acceptable by default)\n• National Identification Number Slip (NINs) in form of paper card\n• Consul ID\n• Digital NIN slip in form of plastic card\n• Digital NIN slip in form of printed A4 sheet\n• Digital NIN slip in form of a PDF document(disabled by default)\n• Digital NIN slip in form of a paper card\n• ECOWAS ID\n• EDO state ID\n• Farmer ID\n• Military ID\n• Navy ID\n• Air Force ID\n• Nursing and Midwifery ID\n• Delta state ID\n• Voter ID\nDriving license\n• Temporary\n• Graduated\nLagos State Resident\nECOWAS Residence Card',
		doctypeCount: 24,
	},
	{
		applicants: 8434,
		forgery: 14,
		percentageForgery: 0.0016599478302110505,
		id: 'NI',
		name: 'Nicaragua',
		conversion: 88.67,
		measure: '%',
		doctype: 'Passport\nID card\n• Voter ID\n• Consul ID\nDriving license\nResidence permit',
		doctypeCount: 6,
	},
	{
		applicants: 57,
		forgery: 4,
		percentageForgery: 0.07017543859649122,
		id: 'NU',
		name: 'Niue',
		conversion: 0,
		measure: '%',
		doctype: 'Driving license',
		doctypeCount: 1,
	},
	{
		applicants: 148368,
		forgery: 374,
		percentageForgery: 0.0025207591933570582,
		id: 'NL',
		name: 'Netherlands',
		conversion: 97.81,
		measure: '%',
		doctype:
			'Passport\n• Travel document\nID card\n• Bonaire ID\n• Diplomatic ID\n• Sint Eustatius ID\n• Saba ID\nDriving license\nResidence permit\n• Refugee ID',
		doctypeCount: 10,
	},
	{
		applicants: 70329,
		forgery: 121,
		percentageForgery: 0.0017204851483740705,
		id: 'NO',
		name: 'Norway',
		conversion: 95.13,
		measure: '%',
		doctype: 'Passport\n• Travel document\nID card\n• Army / Military ID Card\nDriving license\nResidence permit',
		doctypeCount: 6,
	},
	{
		applicants: 144014,
		forgery: 276,
		percentageForgery: 0.001916480342188954,
		id: 'NP',
		name: 'Nepal',
		conversion: 69.03,
		measure: '%',
		doctype:
			'Passport\nID card\n• Armed police force\n• Army ID \n• Voter ID (translation required) \nDriving license\n• Probationary DL',
		doctypeCount: 7,
	},
	{
		applicants: 73,
		forgery: 0,
		percentageForgery: 0,
		id: 'NR',
		name: 'Nauru',
		conversion: 0,
		measure: '%',
		doctype: '',
		doctypeCount: 0,
	},
	{
		applicants: 141652,
		forgery: 318,
		percentageForgery: 0.002244938299494536,
		id: 'NZ',
		name: 'New Zealand',
		conversion: 97.47,
		measure: '%',
		doctype:
			'Passport\nMilitary ID \nDriving license\n• Learner DL\n• Restricted DL\nSticker Residence permit - should be accompanied by main page of the document',
		doctypeCount: 6,
	},
	{
		applicants: 30684,
		forgery: 42,
		percentageForgery: 0.001368791552600704,
		id: 'OM',
		name: 'Oman',
		conversion: 93.6,
		measure: '%',
		doctype: 'Passport\nID card\nDriving license\nResidence permit',
		doctypeCount: 4,
	},
	{
		applicants: 927301,
		forgery: 3626,
		percentageForgery: 0.003910272931874332,
		id: 'PK',
		name: 'Pakistan',
		conversion: 80.82,
		measure: '%',
		doctype:
			'Passport\n• Diplomatic Passport\nID card\n• Overseas Pakistanis\n• ID card (please contact us)\n• Army ID\n• Afghan Citizen Card\n• Pakistan Origin Card\n• Resident of AJK State\n• Person With Disability ID (please contact us)\n• Afghan Citizen Proof of Registration\nDriving license\n• Islamabad\n• Punjab\n• Sindh\n• Khyber\n• Azad Jammu & Kashmir Police\n• Faisalabad\n• Jhang\n• Peshawar\n• Lahore\n• International Driving Permit\n• Balochistan\n• Multan\n• National Highways and Motorway Police\n• Gilgit-baltistan',
		doctypeCount: 26,
	},
	{
		applicants: 5058,
		forgery: 31,
		percentageForgery: 0.006128904705417161,
		id: 'PA',
		name: 'Panama',
		conversion: 94.33,
		measure: '%',
		doctype: 'Passport\nID card\nDriving license\nResidence permit\n• Refugee Residence permit',
		doctypeCount: 5,
	},
	{
		applicants: 14,
		forgery: 0,
		percentageForgery: 0,
		id: 'PN',
		name: 'Pitcairn',
		conversion: 84.37,
		measure: '%',
		doctype: 'Passport',
		doctypeCount: 1,
	},
	{
		applicants: 54904,
		forgery: 503,
		percentageForgery: 0.00916144543202681,
		id: 'PE',
		name: 'Peru',
		conversion: 94.21,
		measure: '%',
		doctype:
			'Passport\nID card\n• Children ID\n• Military ID\n• Certificado de Inscripción\n• Ministerio de Relaciones Exteriores\n• Carné de Solicitante de Refugio\n• Refugee\nDriving license\n• Municipalidad de Huancayo\n• Municipalidad de Cajamarca\n• Municipalidad de Callao\n• Municipalidad de Ica\n• Municipalidad de Canta\n• Municipalidad Mariscal Nieto\n• Municipalidad de Canete\n• Municipalidad de Caylloma\n• Municipalidad de Melgar\n• Municipalidad de Maynas\nResidence permit',
		doctypeCount: 20,
	},
	{
		applicants: 259765,
		forgery: 1046,
		percentageForgery: 0.004026716455257637,
		id: 'PH',
		name: 'Philippines',
		conversion: 80.99,
		measure: '%',
		doctype:
			"Passport\nID card\n• Unified Multi-Purpose ID Card (UMID)\n• PhilHealth ID\n• Postal ID\n• Professional ID\n• Social Security ID\n• Tax ID\n• Armed Forces ID\n• Clearance ID\n• Senior Citizen ID\n• National Police ID\n• Police Clearance Card\n• Barangay ID\n• Persons With Disability ID\n• DSWD Card\n• Veterans Affairs Office ID\n• Bureau of Fire Protection\n• Voter's certification\n• Bureau of Jail Management and Penology ID\n• Solo Parent ID\n• Pambansang Pagkakakilanlan\nDriving license\n• Student Permit\nResidence permit\n• Alien Certificate of Registration\n• Philippine Retirement Authority\n• Alien Employment Permit",
		doctypeCount: 28,
	},
	{
		applicants: 57,
		forgery: 0,
		percentageForgery: 0,
		id: 'PW',
		name: 'Palau',
		conversion: 84.37,
		measure: '%',
		doctype: 'Passport\nDriving license',
		doctypeCount: 2,
	},
	{
		applicants: 1179,
		forgery: 6,
		percentageForgery: 0.005089058524173028,
		id: 'PG',
		name: 'Papua New Guinea',
		conversion: 85.42,
		measure: '%',
		doctype: 'Passport\nID card\nDriving license',
		doctypeCount: 3,
	},
	{
		applicants: 444283,
		forgery: 907,
		percentageForgery: 0.002041491571813461,
		id: 'PL',
		name: 'Poland',
		conversion: 98.5,
		measure: '%',
		doctype:
			'Passport\n• Temporary Passport\nID card\n• Karta Polaka\n• Military ID\n• Special ID\nDriving license\nResidence permit\n• Zezwolenie mały ruch graniczny',
		doctypeCount: 9,
	},
	{
		applicants: 13354,
		forgery: 26,
		percentageForgery: 0.0019469821776246818,
		id: 'PR',
		name: 'Puerto Rico',
		conversion: 79.72,
		measure: '%',
		doctype: 'Passport\nID card\n• Voter ID\n• Firearms license\nDriving license',
		doctypeCount: 5,
	},
	{
		applicants: 61,
		forgery: 0,
		percentageForgery: 0,
		id: 'KP',
		name: 'North Korea',
		conversion: 'Not supported',
		measure: '',
		doctype: '',
		doctypeCount: 0,
	},
	{
		applicants: 170292,
		forgery: 204,
		percentageForgery: 0.001197942357832429,
		id: 'PT',
		name: 'Portugal',
		conversion: 97.01,
		measure: '%',
		doctype:
			'Passport\nID card\n• Refugee ID\nDriving license\nResidence permit\n• EU citizen family member card\n• Permanent Residence EU Citizen card',
		doctypeCount: 7,
	},
	{
		applicants: 3716,
		forgery: 16,
		percentageForgery: 0.004305705059203444,
		id: 'PY',
		name: 'Paraguay',
		conversion: 97.94,
		measure: '%',
		doctype: 'Passport\nID card\nDriving license',
		doctypeCount: 3,
	},
	{
		applicants: 30751,
		forgery: 80,
		percentageForgery: 0.002601541413287373,
		id: 'PS',
		name: 'Palestinian Territory, Occupied',
		conversion: 88.58,
		measure: '%',
		doctype: '',
		doctypeCount: 0,
	},
	{
		applicants: 262,
		forgery: 1,
		percentageForgery: 0.003816793893129771,
		id: 'PF',
		name: 'French Polynesia',
		conversion: 0,
		measure: '%',
		doctype: 'Passport\nID card\nDriving license',
		doctypeCount: 3,
	},
	{
		applicants: 25823,
		forgery: 40,
		percentageForgery: 0.0015490066994539751,
		id: 'QA',
		name: 'Qatar',
		conversion: 90.53,
		measure: '%',
		doctype: 'Passport\nID card\nDriving license\nResidence permit',
		doctypeCount: 4,
	},
	{
		applicants: 1988,
		forgery: 22,
		percentageForgery: 0.011066398390342052,
		id: 'RE',
		name: 'Reunion',
		conversion: 84.37,
		measure: '%',
		doctype: 'Passport\nID card\nDriving license\nResidence permit',
		doctypeCount: 4,
	},
	{
		applicants: 465551,
		forgery: 572,
		percentageForgery: 0.0012286516407439786,
		id: 'RO',
		name: 'Romania',
		conversion: 97.85,
		measure: '%',
		doctype:
			'Passport\n• Refugee document\n• Temporary Passport\nID card\n• Provisional ID\nDriving license\nResidence permit\n• Permis De Mic Trafic De Frontiera',
		doctypeCount: 8,
	},
	{
		applicants: 10729657,
		forgery: 10178,
		percentageForgery: 0.0009485857749227212,
		id: 'RU',
		name: 'Russian Federation',
		conversion: 97.46,
		measure: '%',
		doctype:
			'Passport\n• Internal\n• Foreign\n• Diplomatic\n• Service\n• Refugee\nID card\n• Army / Military ID\n• Temporary Certificate\nDriving license\nResidence permit',
		doctypeCount: 11,
	},
	{
		applicants: 6426,
		forgery: 55,
		percentageForgery: 0.008558979147214442,
		id: 'RW',
		name: 'Rwanda',
		conversion: 76.87,
		measure: '%',
		doctype:
			'Passport\n• Refugee Travel Document\n• Laissez Passer\nID card\n• Refugee ID\nDriving license\nResidence permit',
		doctypeCount: 7,
	},
	{
		applicants: 406052,
		forgery: 315,
		percentageForgery: 0.0007757627101947534,
		id: 'SA',
		name: 'Saudi Arabia',
		conversion: 87.32,
		measure: '%',
		doctype:
			'Passport\n• Diplomatic Passport\n• Special Passport\nID card\n• ID card (non-Latin)\nDriving license\nResidence permit\n• Saudi Premium Residence\n• Residence permit (non-Latin)',
		doctypeCount: 9,
	},
	{
		applicants: 2357,
		forgery: 26,
		percentageForgery: 0.01103097157403479,
		id: 'SD',
		name: 'Sudan',
		conversion: 77.94,
		measure: '%',
		doctype: 'Passport\nID card',
		doctypeCount: 2,
	},
	{
		applicants: 228,
		forgery: 2,
		percentageForgery: 0.008771929824561403,
		id: 'SX',
		name: 'Sint Maarten',
		conversion: 0,
		measure: '%',
		doctype: 'Passport\nID card\nDriving license',
		doctypeCount: 3,
	},
	{
		applicants: 4462,
		forgery: 22,
		percentageForgery: 0.004930524428507396,
		id: 'SN',
		name: 'Senegal',
		conversion: 96.33,
		measure: '%',
		doctype: 'Passport\nID card\n• ECOWAS ID\nDriving license',
		doctypeCount: 4,
	},
	{
		applicants: 64755,
		forgery: 241,
		percentageForgery: 0.003721720330476411,
		id: 'SG',
		name: 'Singapore',
		conversion: 86.08,
		measure: '%',
		doctype:
			"Passport\nID card\n• Home Team National Service Identity Card\nDriving license\nResidence permit\n• Employment Pass\n• Work Permit\n• Student's Pass\n• Dependant's Pass\n• EntrePass",
		doctypeCount: 10,
	},
	{
		applicants: 29,
		forgery: 0,
		percentageForgery: 0,
		id: 'GS',
		name: 'South Georgia And Sandwich Isl.',
		conversion: 84.37,
		measure: '%',
		doctype: '',
		doctypeCount: 0,
	},
	{
		applicants: 51,
		forgery: 10,
		percentageForgery: 0.19607843137254902,
		id: 'SH',
		name: 'Saint Helena',
		conversion: 84.47,
		measure: '%',
		doctype: 'Passport',
		doctypeCount: 1,
	},
	{
		applicants: 20,
		forgery: 1,
		percentageForgery: 0.05,
		id: 'SJ',
		name: 'Svalbard And Jan Mayen',
		conversion: 84.37,
		measure: '%',
		doctype: '',
		doctypeCount: 0,
	},
	{
		applicants: 156,
		forgery: 1,
		percentageForgery: 0.00641025641025641,
		id: 'SB',
		name: 'Solomon Islands',
		conversion: 84.37,
		measure: '%',
		doctype: 'Passport\nVoter ID\nDriving license',
		doctypeCount: 3,
	},
	{
		applicants: 940,
		forgery: 5,
		percentageForgery: 0.005319148936170213,
		id: 'SL',
		name: 'Sierra Leone',
		conversion: 75.47,
		measure: '%',
		doctype: 'Passport\nID card\n• Voter card\nDriving license',
		doctypeCount: 4,
	},
	{
		applicants: 11962,
		forgery: 38,
		percentageForgery: 0.003176726299949841,
		id: 'SV',
		name: 'El Salvador',
		conversion: 95.33,
		measure: '%',
		doctype: 'Passport\nID card\nDriving license\nResidence permit',
		doctypeCount: 4,
	},
	{
		applicants: 343,
		forgery: 3,
		percentageForgery: 0.008746355685131196,
		id: 'SM',
		name: 'San Marino',
		conversion: 89.38,
		measure: '%',
		doctype: 'Passport\nID card\nDriving license',
		doctypeCount: 3,
	},
	{
		applicants: 2322,
		forgery: 23,
		percentageForgery: 0.009905254091300603,
		id: 'SO',
		name: 'Somalia',
		conversion: 75.27,
		measure: '%',
		doctype: 'Passport\nID card\nDriving license',
		doctypeCount: 3,
	},
	{
		applicants: 13,
		forgery: 0,
		percentageForgery: 0,
		id: 'PM',
		name: 'Saint Pierre And Miquelon',
		conversion: 0,
		measure: '%',
		doctype: 'Passport\nID card',
		doctypeCount: 2,
	},
	{
		applicants: 22777,
		forgery: 92,
		percentageForgery: 0.004039162312859464,
		id: 'RS',
		name: 'Serbia',
		conversion: 98.9,
		measure: '%',
		doctype: 'Passport\nID card\n• Diplomatic ID\nDriving license\n• Probationary DL\nResidence permit',
		doctypeCount: 6,
	},
	{
		applicants: 310,
		forgery: 0,
		percentageForgery: 0,
		id: 'SS',
		name: 'South Sudan',
		conversion: 0,
		measure: '%',
		doctype: 'Passport\nID card\nDriving license',
		doctypeCount: 3,
	},
	{
		applicants: 142,
		forgery: 1,
		percentageForgery: 0.007042253521126761,
		id: 'ST',
		name: 'Sao Tome and Principe',
		conversion: 74.92,
		measure: '%',
		doctype: 'Passport\nID card',
		doctypeCount: 2,
	},
	{
		applicants: 831,
		forgery: 11,
		percentageForgery: 0.013237063778580024,
		id: 'SR',
		name: 'Suriname',
		conversion: 85.37,
		measure: '%',
		doctype: 'Passport\nID card\nDriving license',
		doctypeCount: 3,
	},
	{
		applicants: 87107,
		forgery: 157,
		percentageForgery: 0.0018023809797146038,
		id: 'SK',
		name: 'Slovakia',
		conversion: 97.81,
		measure: '%',
		doctype: 'Passport\nID card\nDriving license\n• Paper card\nResidence permit',
		doctypeCount: 5,
	},
	{
		applicants: 86110,
		forgery: 203,
		percentageForgery: 0.0023574497735454653,
		id: 'SI',
		name: 'Slovenia',
		conversion: 97.66,
		measure: '%',
		doctype: 'Passport\nID card\nDriving license\nResidence permit\n• Family Member Card',
		doctypeCount: 5,
	},
	{
		applicants: 129622,
		forgery: 206,
		percentageForgery: 0.0015892363950563947,
		id: 'SE',
		name: 'Sweden',
		conversion: 98.01,
		measure: '%',
		doctype:
			'Passport\n• Emergency Passport\n• Diplomatic Passport\nID card\n• Tax ID\n• Identitetskort\nDriving license\nResidence permit',
		doctypeCount: 8,
	},
	{
		applicants: 2942,
		forgery: 33,
		percentageForgery: 0.011216859279401768,
		id: 'SZ',
		name: 'Swaziland',
		conversion: 75.97,
		measure: '%',
		doctype: 'Passport\nID card\nDriving license',
		doctypeCount: 3,
	},
	{
		applicants: 636,
		forgery: 1,
		percentageForgery: 0.0015723270440251573,
		id: 'SC',
		name: 'Seychelles',
		conversion: 75.02,
		measure: '%',
		doctype: 'Passport\nID card\nDriving license',
		doctypeCount: 3,
	},
	{
		applicants: 3938,
		forgery: 36,
		percentageForgery: 0.009141696292534281,
		id: 'SY',
		name: 'Syria',
		conversion: 77.54,
		measure: '%',
		doctype:
			'Passport\nID card (non-Latin) \nDriving license (non-Latin) \n• Booklet DL\n• Paper card license (non-latin)',
		doctypeCount: 5,
	},
	{
		applicants: 172,
		forgery: 1,
		percentageForgery: 0.005813953488372093,
		id: 'TC',
		name: 'Turks And Caicos Islands',
		conversion: 84.47,
		measure: '%',
		doctype: 'Passport\nID card \nDriving license',
		doctypeCount: 3,
	},
	{
		applicants: 989,
		forgery: 6,
		percentageForgery: 0.006066734074823054,
		id: 'TD',
		name: 'Chad',
		conversion: 84.72,
		measure: '%',
		doctype: 'Passport\nDriving license\nID card\n• Voter card\nResidence permit',
		doctypeCount: 5,
	},
	{
		applicants: 11721,
		forgery: 40,
		percentageForgery: 0.003412678099138299,
		id: 'TG',
		name: 'Togo',
		conversion: 92.13,
		measure: '%',
		doctype:
			'Passport\nID card\n• Voter card\n• Consul ID\n• Police ID\n• Army / Military ID\nDriving license\nResidence permit',
		doctypeCount: 8,
	},
	{
		applicants: 314712,
		forgery: 402,
		percentageForgery: 0.0012773583466788683,
		id: 'TH',
		name: 'Thailand',
		conversion: 93.36,
		measure: '%',
		doctype:
			'Passport\n• Border Passport\n• Emergency Passport\nID card\n• Army ID\n• Card for not registered\n• Persons with Disabilities ID\n• Radio Operator license\nDriving license\n• Temporary DL\n• Public Vehicle DL\n• Life Time DL\nResidence permit\n• Work Permit',
		doctypeCount: 14,
	},
	{
		applicants: 107603,
		forgery: 38,
		percentageForgery: 0.00035315000511138163,
		id: 'TJ',
		name: 'Tajikistan',
		conversion: 98.32,
		measure: '%',
		doctype: 'Passport\nID card\nDriving license',
		doctypeCount: 3,
	},
	{
		applicants: 9,
		forgery: 0,
		percentageForgery: 0,
		id: 'TK',
		name: 'Tokelau',
		conversion: 0,
		measure: '%',
		doctype: '',
		doctypeCount: 0,
	},
	{
		applicants: 10749,
		forgery: 30,
		percentageForgery: 0.0027909572983533353,
		id: 'TM',
		name: 'Turkmenistan',
		conversion: 95.14,
		measure: '%',
		doctype: 'Passport\n• Internal\n• Foreign\nDriving license',
		doctypeCount: 4,
	},
	{
		applicants: 65,
		forgery: 1,
		percentageForgery: 0.015384615384615385,
		id: 'TL',
		name: 'Timor-Leste',
		conversion: 77.07,
		measure: '%',
		doctype: 'Passport\nDriving license\nVoter card',
		doctypeCount: 3,
	},
	{
		applicants: 196,
		forgery: 0,
		percentageForgery: 0,
		id: 'TO',
		name: 'Tonga',
		conversion: 74.92,
		measure: '%',
		doctype: 'Passport\nID card\nDriving license',
		doctypeCount: 3,
	},
	{
		applicants: 9118,
		forgery: 51,
		percentageForgery: 0.005593331871024347,
		id: 'TT',
		name: 'Trinidad and Tobago',
		conversion: 97.2,
		measure: '%',
		doctype: 'Passport\nID card\nDriving license\nResidence permit',
		doctypeCount: 4,
	},
	{
		applicants: 9320,
		forgery: 97,
		percentageForgery: 0.010407725321888411,
		id: 'TN',
		name: 'Tunisia',
		conversion: 75.48,
		measure: '%',
		doctype: 'Passport\n• Diplomatic Passport\nID card (non-Latin)\nDriving license\nResidence permit',
		doctypeCount: 5,
	},
	{
		applicants: 307708,
		forgery: 1014,
		percentageForgery: 0.0032953319380711584,
		id: 'TR',
		name: 'Turkey',
		conversion: 96.33,
		measure: '%',
		doctype:
			'Passport\nID card\n• Diplomatic ID\n• Gecici Koruma Kimlik Belgesi\n• Uluslararasi Koruma Basvuru Sahibi Kimlik Belgesi\n• Blue Card\nDriving license\nResidence permit\n• Work Permit',
		doctypeCount: 9,
	},
	{
		applicants: 51,
		forgery: 0,
		percentageForgery: 0,
		id: 'TV',
		name: 'Tuvalu',
		conversion: 84.52,
		measure: '%',
		doctype: 'Passport\nDriving license',
		doctypeCount: 2,
	},
	{
		applicants: 110171,
		forgery: 175,
		percentageForgery: 0.001588439789055196,
		id: 'TW',
		name: 'Taiwan',
		conversion: 94.73,
		measure: '%',
		doctype:
			'Passport\nID card \n• National Health Insurance\nDriving license \nResidence permit \n• RP Sticker - should be accompanied by main page of the document',
		doctypeCount: 6,
	},
	{
		applicants: 12548,
		forgery: 241,
		percentageForgery: 0.019206248007650622,
		id: 'TZ',
		name: 'Tanzania',
		conversion: 86.24,
		measure: '%',
		doctype:
			'Passport\nID card\n• Voter ID\n• Zanzibari Card\n• Health Insurance\n• Zanzibar Voter ID\nDriving license\n• Zanzibar DL\nResidence permit\n• E-Permit Card',
		doctypeCount: 10,
	},
	{
		applicants: 15523,
		forgery: 599,
		percentageForgery: 0.038587901823101206,
		id: 'UG',
		name: 'Uganda',
		conversion: 95.52,
		measure: '%',
		doctype: 'Passport\nID card\n• Refugee ID\n• Voter Location Slip\nDriving license',
		doctypeCount: 5,
	},
	{
		applicants: 1122365,
		forgery: 2974,
		percentageForgery: 0.0026497618867302526,
		id: 'UA',
		name: 'Ukraine',
		conversion: 91.64,
		measure: '%',
		doctype:
			'Passport\n• Temporary Certificate of Citizenship\n• Travel Document of Person Granted Complementary Protection\n• Internal old passport (at request)\nID card\n• Army ID\n• Pension Certificate\nDriving license\nResidence permit\n• Temporary Residence permit\n• Permanent Residence permit',
		doctypeCount: 11,
	},
	{
		applicants: 982,
		forgery: 14,
		percentageForgery: 0.014256619144602852,
		id: 'UM',
		name: 'United States Minor Outlying Islands',
		conversion: 0,
		measure: '%',
		doctype: '',
		doctypeCount: 0,
	},
	{
		applicants: 6418,
		forgery: 28,
		percentageForgery: 0.004362729822374571,
		id: 'UY',
		name: 'Uruguay',
		conversion: 97.7,
		measure: '%',
		doctype:
			'Passport\nID card\nDriving license\n• Permiso Único Nacional de Conducir\n• Intendencia Municipal de Maldonado',
		doctypeCount: 5,
	},
	{
		applicants: 2116975,
		forgery: 5626,
		percentageForgery: 0.0026575656302034742,
		id: 'US',
		name: 'United States',
		conversion: 91.64,
		measure: '%',
		doctype:
			'Passport\n• Emergency Passport\n• Refugee Travel Document\nID card\n• Alabama ID\n• Alabama Pistol Permit\n• Alabama Photo Voter Identification Card\n• Alabama Photo Voter Identification Card Temporary\n• Alaska ID\n• Alaska Curyung Tribal Council ID\n• Arizona ID\n• Arkansas ID\n• California ID\n• City ID\n• Colorado ID\n• Connecticut ID\n• Delaware ID\n• Department of Defense USID Card\n• Florida ID\n• Florida Firearm license\n• Georgia ID\n• Georgia Voter ID Card\n• Georgia Firearm license\n• Hawaii ID\n• Hawaii ID Temporal\n• Idaho ID\n• Illinois Firearm ID\n• Illinois ID\n• Illinois Temporary ID\n• Indiana ID\n• Iowa ID\n• Kansas ID\n• Kentucky ID\n• Louisiana ID\n• Maine ID\n• Maryland ID\n• Massachusetts ID\n• Massachusetts Firearm license\n• Medical ID\n• Michigan ID\n• Michigan Enhanced ID\n• Common Access Card (Military ID United States Government)\n• Minnesota ID\n• Mississippi ID\n• Missouri ID\n• Missouri Temporary ID\n• Montana ID\n• Montana Temporary ID\n• Nebraska ID\n• Nevada ID\n• New Hampshire ID\n• New Hampshire Temporary ID\n• New Jersey ID\n• New Mexico ID\n• New York ID\n• New York Enhanced ID\n• New York Medical Marijuana Program Registry ID\n• North Carolina ID\n• North Dakota ID\n• Ohio ID\n• United States Veteran Ohio ID\n• Oklahoma ID\n• Oklahoma Medical Marijuana Patient Card\n• Oklahoma Firearm license\n• Oregon ID\n• Oregon Limited-term ID\n• Passport Card\n• Pennsylvania ID\n• Pennsylvania Firearm license\n• Rhode Island ID\n• South Carolina ID\n• South Carolina Firearm license\n• South Dakota ID\n• Tennessee ID\n• Texas ID\n• Texas Firearm license\n• Texas Private Security Registration\n• Texas Limited-term ID\n• Tribal ID\n• United States Uniformed Services ID\n• United States Department of State ID\n• Utah ID\n• Utah Firearm license\n• Vermont ID\n• Virginia ID\n• Washington ID\n• Washington Enhanced ID\n• Washington DC ID\n• West Virginia ID\n• Wisconsin ID\n• Wyoming ID\nDriving license\n• Alabama DL\n• Alabama Temporary DL\n• Alaska DL\n• Alaska Commercial DL\n• Arizona DL\n• Arizona Commercial DL\n• Arizona Instruction Permit\n• Arkansas DL\n• Arkansas Commercial DL\n• California Commercial DL\n• California DL\n• Colorado DL\n• Colorado Commercial DL\n• Colorado Restricted Permit\n• Colorado Temporary DL\n• Colorado Instruction Permit\n• Connecticut DL\n• Connecticut Adult Learner Permit\n• Delaware DL\n• Enhanced Driver license\n• Florida DL\n• Florida Temporary DL\n• Florida Commercial DL\n• Florida Learner’s license\n• Georgia DL\n• Georgia Commercial DL\n• Georgia Instructional Permit\n• Hawaii DL\n• Hawaii Temporary DL\n• Hawaii Limited Purpose DL\n• Idaho DL\n• Idaho Commercial DL\n• Idaho Temporary DL\n• Illinois DL\n• Illinois Commercial DL\n• Illinois Temporary DL\n• Indiana DL\n• Indiana Learner Permit\n• Indiana Temporary DL\n• Iowa DL\n• Iowa Instruction Permit\n• Iowa Temporary DL\n• Kansas DL\n• Kansas Commercial DL\n• Kentucky DL\n• Kentucky Instruction Permit\n• Kentucky Commercial DL\n• Kentucky Temporary DL\n• Louisiana DL\n• Louisiana Commercial DL\n• Maine DL\n• Maine Commercial DL\n• Maryland DL\n• Maryland Provisional DL\n• Maryland Learner’s Instructional Permit\n• Massachusetts DL\n• Massachusetts Junior Operator’s license\n• Michigan DL\n• Michigan Commercial DL\n• Michigan Graduated DL\n• Minnesota DL\n• Minnesota Instruction Permit\n• Minnesota Provisional DL\n• Minnesota Temporary DL\n• Mississippi DL\n• Mississippi Commercial DL\n• Missouri DL\n• Missouri Commercial DL\n• Missouri Temporary DL\n• Montana DL\n• Montana Temporary DL\n• Nebraska DL\n• Nebraska Operator license\n• Nebraska Ignition Interlock Permit\n• Nevada DL\n• New Hampshire DL\n• New Hampshire Operator license\n• New Hampshire Youth Operator license\n• New Jersey DL\n• New Jersey Probationary Auto license\n• New Jersey Commercial DL\n• New Mexico DL\n• New Mexico Provisional DL\n• New York DL\n• New York Learner Permit\n• New York Commercial DL\n• New York Temporary Visitor DL\n• North Carolina DL\n• North Carolina Commercial DL\n• North Carolina Temporary DL\n• North Carolina Limited Provisional license\n• North Dakota DL\n• North Dakota Commercial DL\n• Ohio DL\n• Ohio Temporary Instruction Permit\n• Ohio Commercial DL\n• Ohio Temporary Permit\n• Ohio Ignition Interlock license\n• Oklahoma DL\n• Oklahoma Learner Permit\n• Oklahoma Commercial DL\n• Oregon DL\n• Oregon Provisional DL\n• Oregon Instruction Permit\n• Oregon Provisional Instruction Permit\n• Oregon Interim license\n• Oregon Commercial DL\n• Pennsylvania DL\n• Pennsylvania Junior DL\n• Pennsylvania Interim DL\n• Rhode Island DL\n• South Carolina DL\n• South Carolina Limited-term DL\n• South Carolina Limited-term Commercial DL\n• South Carolina Beginner’s Permit\n• South Dakota DL\n• South Dakota Commercial DL\n• Tennessee DL\n• Tennessee Learner Permit\n• Tennessee Commercial DL\n• Tennessee Temporary DL\n• Tennessee Intermediate Restricted DL\n• Texas DL\n• Texas Commercial DL\n• Texas Limited-term DL\n• Texas Temporary Permit\n• Utah DL\n• Utah Temporary DL\n• United States Department of State DL\n• Vermont DL\n• Vermont Driver’s Privilege Card\n• Vermont Learner’s Permit\n• Virginia DL\n• Virginia Learner’s Permit\n• Washington DL\n• Washington Intermediate DL\n• Washington Instruction Permit\n• Washington DC DL\n• Washington DC Temporary DL\n• Washington DC Learner Permit\n• Washington DC Temporary Learner Permit\n• West Virginia DL\n• Wisconsin DL\n• Wisconsin Instruction Permit\n• Wisconsin Interim license\n• Wyoming Commercial DL\n• Wyoming DL\nResidence permit\n• Green Card\n• Work Permit\n• NEXUS Card\n• Border Crossing Card\n• Global Entry Customs Card',
		doctypeCount: 245,
	},
	{
		applicants: 284658,
		forgery: 289,
		percentageForgery: 0.0010152533917894455,
		id: 'UZ',
		name: 'Uzbekistan',
		conversion: 95.41,
		measure: '%',
		doctype:
			'Passport\n• Internal (green) passport\n• Foreign (claret) passport\n• Certificate of Return to Uzbekistan\nID card\n• Persons Without Citizenship ID card\nDriving license\nResidence permit',
		doctypeCount: 8,
	},
	{
		applicants: 57,
		forgery: 0,
		percentageForgery: 0,
		id: 'VA',
		name: 'Vatican City State',
		conversion: 89.13,
		measure: '%',
		doctype: 'Passport',
		doctypeCount: 1,
	},
	{
		applicants: 620,
		forgery: 1,
		percentageForgery: 0.0016129032258064516,
		id: 'VC',
		name: 'Saint Vincent And Grenadines',
		conversion: 84.87,
		measure: '%',
		doctype: 'Passport\nID card \nDriving license',
		doctypeCount: 3,
	},
	{
		applicants: 335435,
		forgery: 3189,
		percentageForgery: 0.009507057999314323,
		id: 'VE',
		name: 'Venezuela',
		conversion: 93.73,
		measure: '%',
		doctype: 'Passport\nID card\n• Carnet de la Patria\nDriving license\nResidence permit',
		doctypeCount: 5,
	},
	{
		applicants: 322,
		forgery: 1,
		percentageForgery: 0.003105590062111801,
		id: 'VG',
		name: 'Virgin Islands, British',
		conversion: 84.77,
		measure: '%',
		doctype: 'Passport\nDriving license \nResidence permit',
		doctypeCount: 4,
	},
	{
		applicants: 656,
		forgery: 1,
		percentageForgery: 0.001524390243902439,
		id: 'VI',
		name: 'Virgin Islands, U.S.',
		conversion: 84.57,
		measure: '%',
		doctype: 'Passport\nID card \nDriving license \n• Temporary DL',
		doctypeCount: 4,
	},
	{
		applicants: 325850,
		forgery: 1219,
		percentageForgery: 0.0037409851158508515,
		id: 'VN',
		name: 'Vietnam',
		conversion: 89.3,
		measure: '%',
		doctype:
			'Passport\n• Entry and Exit Permit\nID card\n• Military ID\nDriving license\n• Army DL\nResidence permit\n• Temporary Resident Card\n• Permanent Resident Card\n• Certificate of Visa Exemption',
		doctypeCount: 10,
	},
	{
		applicants: 175,
		forgery: 2,
		percentageForgery: 0.011428571428571429,
		id: 'VU',
		name: 'Vanuatu',
		conversion: 84.52,
		measure: '%',
		doctype: 'Passport\nID card\n• VNPF Member ID card\nDriving license',
		doctypeCount: 4,
	},
	{
		applicants: 7,
		forgery: 0,
		percentageForgery: 0,
		id: 'WF',
		name: 'Wallis and Futuna',
		conversion: 84.37,
		measure: '%',
		doctype: 'Passport\nID card',
		doctypeCount: 2,
	},
	{
		applicants: 280,
		forgery: 1,
		percentageForgery: 0.0035714285714285713,
		id: 'WS',
		name: 'Samoa',
		conversion: 75.12,
		measure: '%',
		doctype: 'Passport\nID card\nDriving license',
		doctypeCount: 3,
	},
	{
		applicants: 40,
		forgery: 0,
		percentageForgery: 0,
		id: 'XK',
		name: 'Kosovo',
		conversion: 91.48,
		measure: '%',
		doctype: 'Passport\nID card\nDriving license',
		doctypeCount: 3,
	},
	{
		applicants: 9140,
		forgery: 27,
		percentageForgery: 0.002954048140043764,
		id: 'YE',
		name: 'Yemen',
		conversion: 70.83,
		measure: '%',
		doctype: 'Passport\n• Special Passport\n• Diplomatic Passport\nID card\n• Refugee ID\nDriving license',
		doctypeCount: 5,
	},
	{
		applicants: 306543,
		forgery: 1560,
		percentageForgery: 0.00508900871982071,
		id: 'ZA',
		name: 'South Africa',
		conversion: 88.92,
		measure: '%',
		doctype:
			'Passport\n• Refugee Travel Document\nID card\n• Booklet ID\n• Refugee Booklet \n• Temporary ID\nResidence permit\n• Asylum Seeker Temporary Permit\n• Formal Recognition of Refugee',
		doctypeCount: 8,
	},
	{
		applicants: 7148,
		forgery: 89,
		percentageForgery: 0.012451035254616676,
		id: 'ZM',
		name: 'Zambia',
		conversion: 87.88,
		measure: '%',
		doctype:
			'Passport\nID card\n• Voter ID\nDriving license\n• Provisional DL\nResidence permit\n• Study Permit\n• Employment Permit\n• Work permit\n• Commonwealth Registration Card',
		doctypeCount: 10,
	},
	{
		applicants: 10765,
		forgery: 220,
		percentageForgery: 0.020436600092893636,
		id: 'ZW',
		name: 'Zimbabwe',
		conversion: 79.07,
		measure: '%',
		doctype: 'Passport\nID card\n• Metal ID\nDriving license',
		doctypeCount: 4,
	},
]
